import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";
import Providers from "./providers";
import HeroNavBar from "@/components/homepage/Header/HeroNavBar";
import CookieConsent from "@/components/common/CookieConsent";

export const metadata: Metadata = {
  title: "Faraon",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className} suppressHydrationWarning>
        <HolyLoader color="#868686" />
        <Providers>
          <TopNavbar />
          <HeroNavBar />
          <div className="pt-16">{children}</div>
          <Footer />
          <CookieConsent />
        </Providers>
      </body>
    </html>
  );
}
